version: '3'

services: 
  node:
    build:
      context: node
    container_name: node
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./node:/user/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    command: npm run start
    depends_on:
      - db

  react:
    build:
      context: react
    container_name: react
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./react:/usr/src/app
      - /usr/src/app/node_modules
      tty: true
      ports:
        - "5173:5173"
      command: npm run

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - :8080:80"
    networks:
      - node-network
    depends_on:
      - node
      - react

  db:
    image: postgres
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
    PORTS:
      - "5432:5432"
    networks:
      node-network

networks:
  node_network:
    driver: bridge